version: '3.8'

services:
  postgres:
    image: postgres
    container_name: my-postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:
